# Python基础

# 数据读取

1.读取用户信息表、银行账单表以及信用卡账单表

In [76]:
import pandas as pd
userinfo_df = pd.read_csv(r"D:\WeChat Files\wxid_vzlr2hkxrgil22\FileStorage\File\2024-09\userinfo.csv")
userinfo_df.head(5)

                        new_user_id 性别  职业   教育程度 婚姻状态  户口类型
0  7259fe272934e0dc348092c37544a445  女  公职  本科及以上   未婚  集体户口
1  0c87f6b1f7e0350a35841ba34df9d26a  男  公职  本科及以上   离异  集体户口
2  74c53a62f15cc039864aefc41170f81b  男  公职     大专   离异  家庭户口
3  211f56f356fa6ecc6334bb73e52c7b16  男  企业     高中   离异  农业户口
4  07b0d9ac7924424894141b2fecfa0ee0  男  公职  本科及以上   已婚  集体户口

2.读取逾期表，并将第一列删掉

In [77]:
overdue_df = pd.read_csv(r"D:\WeChat Files\wxid_vzlr2hkxrgil22\FileStorage\File\2024-09\overdue.csv")
overdue_df.head(5)

   Unnamed: 0                       new_user_id  标签         分数
0           0  eddcaa8984f8db5199ec28323efb18a4   0  51.846690
1           1  65b01fba105ee82613babff7c88929c5   1  70.242250
2           2  968083a2d1a7e6b5b85a66b0bc412830   1  73.397476
3           3  18aeed58fd39a58cc1430a3a417ed7a9   1  55.463276
4           4  bae4896cea4a34616ae3babca11439ae   1  54.754932

In [78]:
overdue_df.drop(['Unnamed: 0'],axis=1,inplace=True)
overdue_df.columns=['new_user_id','违约','分数']
overdue_df

                           new_user_id  违约         分数
0     eddcaa8984f8db5199ec28323efb18a4   0  51.846690
1     65b01fba105ee82613babff7c88929c5   1  70.242250
2     968083a2d1a7e6b5b85a66b0bc412830   1  73.397476
3     18aeed58fd39a58cc1430a3a417ed7a9   1  55.463276
4     bae4896cea4a34616ae3babca11439ae   1  54.754932
...                                ...  ..        ...
9995  aef033946bf25d056d1bc01f28b397d5   0  52.179243
9996  b3b457750eb9d6941fce9d1258003879   1  57.013629
9997  f5858c654e97bd9d03fb9131a2a12dd8   0  52.002452
9998  6989c7588f79c186a0895e6e9a70efa8   0  55.380466
9999  62949e7c9eb23cd2440dd30be7f07bba   0  52.969022

[10000 rows x 3 columns]

# 离散变量

3.统计用户信息表中“职业”变量有几个属性，户口类型有几个属性，并将这些属性用顺序编码的方式来进行编码

In [79]:
userinfo_df['户口类型'].unique()

array(['集体户口', '家庭户口', '农业户口', '其他户口', '未知'], dtype=object)

In [80]:
userinfo_df=userinfo_df.replace({'性别':{'女':0,'男':1,'未知':2}})
print(userinfo_df.head())

                        new_user_id  性别  职业   教育程度 婚姻状态  户口类型
0  7259fe272934e0dc348092c37544a445   0  公职  本科及以上   未婚  集体户口
1  0c87f6b1f7e0350a35841ba34df9d26a   1  公职  本科及以上   离异  集体户口
2  74c53a62f15cc039864aefc41170f81b   1  公职     大专   离异  家庭户口
3  211f56f356fa6ecc6334bb73e52c7b16   1  企业     高中   离异  农业户口
4  07b0d9ac7924424894141b2fecfa0ee0   1  公职  本科及以上   已婚  集体户口

C:\Users\27968\AppData\Local\Temp\ipykernel_41384\1231349988.py:1: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [81]:
def todict(col):
    res={}
    cnt=0
    for e in col.unique():
        res[e]=cnt
        cnt+=1
    return res

4.统计“教育程度”中每个属性出现的次数

In [82]:
userinfo_df['教育程度'].value_counts()

教育程度
大专       4227
本科及以上    4131
高中       1547
未知         53
初中及以下      42
Name: count, dtype: int64

# 连续变量

5.显示银行账单表中“交易金额”的不同统计量

In [83]:
bank_df = pd.read_csv(r"D:\WeChat Files\wxid_vzlr2hkxrgil22\FileStorage\File\2024-09\bank.csv")
bank_df.head(5)

,new_user_id,交易时间戳,交易类型,交易金额,工资收入标记,交易时间,交易年,交易月,交易日,交易时,交易分,交易秒
0,65b01fba105ee82613babff7c88929c5,58848407247,1,43.757548,0,2156-06-25 21:58:44,2156,6,25,21,58,44
1,65b01fba105ee82613babff7c88929c5,58849365297,1,42.143743,0,2156-06-27 00:35:29,2156,6,27,0,35,29
2,65b01fba105ee82613babff7c88929c5,58850118237,1,40.189051,0,2156-06-27 21:30:23,2156,6,27,21,30,23
3,65b01fba105ee82613babff7c88929c5,58850118447,1,40.189051,0,2156-06-27 21:30:44,2156,6,27,21,30,44
4,65b01fba105ee82613babff7c88929c5,58850244487,1,40.189051,0,2156-06-28 01:00:48,2156,6,28,1,0,48

In [84]:
bank_df['交易金额'].describe()

count    1.068424e+06
mean     4.341593e+01
std      3.052264e+00
min      3.056884e+01
25%      4.187518e+01
50%      4.375755e+01
75%      4.555948e+01
max      5.474213e+01
Name: 交易金额, dtype: float64

6.将银行账单按'交易金额','交易时间'进行降序排列，并打印输出

In [85]:
bank_df.sort_values(by = ['交易金额','交易时间'],ascending=False)
bank_df

,new_user_id,交易时间戳,交易类型,交易金额,工资收入标记,交易时间,交易年,交易月,交易日,交易时,交易分,交易秒
0,65b01fba105ee82613babff7c88929c5,58848407247,1,43.757548,0,2156-06-25 21:58:44,2156,6,25,21,58,44
1,65b01fba105ee82613babff7c88929c5,58849365297,1,42.143743,0,2156-06-27 00:35:29,2156,6,27,0,35,29
2,65b01fba105ee82613babff7c88929c5,58850118237,1,40.189051,0,2156-06-27 21:30:23,2156,6,27,21,30,23
3,65b01fba105ee82613babff7c88929c5,58850118447,1,40.189051,0,2156-06-27 21:30:44,2156,6,27,21,30,44
4,65b01fba105ee82613babff7c88929c5,58850244487,1,40.189051,0,2156-06-28 01:00:48,2156,6,28,1,0,48
...,...,...,...,...,...,...,...,...,...,...,...,...
1068419,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.749626,0,2157-10-01 07:31:27,2157,10,1,7,31,27
1068420,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.313940,0,2157-10-01 07:31:27,2157,10,1,7,31,27
1068421,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.313940,0,2157-10-01 07:31:27,2157,10,1,7,31,27
1068422,8909c0bd8a030659a64af64874f3a85d,59248782877,0,45.556734,0,2157-10-02 07:31:27,2157,10,2,7,31,27
1068423,8909c0bd8a030659a64af64874f3a85d,59248782877,0,42.864229,0,2157-10-02 07:31:27,2157,10,2,7,31,27

# 数据查询

7.查询“职业”为公职的用户，并打印输出用户编号、职业、户口类型

In [86]:
userinfo_df.loc[(userinfo_df['职业']=='公职'),['new_user_id','职业','户口类型']]

                           new_user_id  职业  户口类型
0     7259fe272934e0dc348092c37544a445  公职  集体户口
1     0c87f6b1f7e0350a35841ba34df9d26a  公职  集体户口
2     74c53a62f15cc039864aefc41170f81b  公职  家庭户口
4     07b0d9ac7924424894141b2fecfa0ee0  公职  集体户口
6     f252acaac66355ee480542cb658036f9  公职  集体户口
...                                ...  ..   ...
9993  546d27488df8de96f92f1a787c0406d1  公职  其他户口
9994  97508506214c4f35c72ef03e287fc701  公职  家庭户口
9995  6b8887024b4258aab9c7b655fd2a718f  公职  农业户口
9996  158dd40361cd883d37a30fc448cfa7da  公职  集体户口
9997  12fd60bba16cb55cdf3ca81d7d3326b5  公职  其他户口

[7392 rows x 3 columns]

8.查询'户口类型'为'农业户口'并且'性别'为'女'的用户,并打印输出其用户编号、性别、职业、户口类型

In [87]:
userinfo_df.loc[(userinfo_df['户口类型']=='农业户口')&(userinfo_df['性别']=='女'),['new_user_id','性别','职业','户口类型']]

Empty DataFrame
Columns: [new_user_id, 性别, 职业, 户口类型]
Index: []

# 数据质量

9.统计用户信息表中的缺失值，并打印输出

In [88]:
userinfo_df.isna().sum()

new_user_id    0
性别             0
职业             2
教育程度           0
婚姻状态           1
户口类型           0
dtype: int64

10.画出信用卡账单表中'信用卡额度'的箱线图，并查看异常值

In [89]:
import plotly.express as px

In [90]:
userinfo_df.columns

Index(['new_user_id', '性别', '职业', '教育程度', '婚姻状态', '户口类型'], dtype='object')

In [91]:
userinfo_df["职业"] = userinfo_df["职业"].map({'公职':0,'企业':1,'事业单位':2,'无业':3,'学生':4})

In [92]:
overdue_df.columns

Index(['new_user_id', '违约', '分数'], dtype='object')

In [93]:
occupation = userinfo_df[["new_user_id","职业"]]
default = overdue_df[["new_user_id","分数"]]
data = pd.merge(occupation, default, how="outer", on="new_user_id")
data

                           new_user_id   职业         分数
0     0000a11bede26d01990cd7bf86a4ffed  0.0  55.132676
1     0001102f53f24a8952ed5b47f9564354  0.0  51.653801
2     000228d848615f1320914e0cf6064d12  0.0  53.857591
3     0003f283dfacd7100bba76d876cf94da  1.0  75.498352
4     000fc975cf7a868719446414a5034eae  2.0  53.199382
...                                ...  ...        ...
9995  ffe67dcf29be13aaea8203c7e1f78e52  0.0  54.371003
9996  ffea401657d40332181dc2b2ef814553  0.0  82.399401
9997  ffeac4580f594e7fc0d98f6ba53755e3  0.0  54.994612
9998  ffed832f763c51fe6d055eae506f9ebf  1.0  56.880434
9999  fff9adcad0dae52e4efe806da7821cbc  0.0  53.748123

[10000 rows x 3 columns]

In [94]:
px.scatter(y=data['分数'],x=data['职业'])

In [95]:
occupation1 = userinfo_df[["new_user_id","职业"]]
default1 = overdue_df[["new_user_id","违约"]]
weiyue_data = pd.merge(occupation1, default1, how="outer", on="new_user_id")
weiyue_data

                           new_user_id   职业  违约
0     0000a11bede26d01990cd7bf86a4ffed  0.0   0
1     0001102f53f24a8952ed5b47f9564354  0.0   0
2     000228d848615f1320914e0cf6064d12  0.0   0
3     0003f283dfacd7100bba76d876cf94da  1.0   1
4     000fc975cf7a868719446414a5034eae  2.0   0
...                                ...  ...  ..
9995  ffe67dcf29be13aaea8203c7e1f78e52  0.0   0
9996  ffea401657d40332181dc2b2ef814553  0.0   1
9997  ffeac4580f594e7fc0d98f6ba53755e3  0.0   0
9998  ffed832f763c51fe6d055eae506f9ebf  1.0   0
9999  fff9adcad0dae52e4efe806da7821cbc  0.0   0

[10000 rows x 3 columns]

In [96]:
size=weiyue_data.groupby(['职业','违约'])['new_user_id'].agg(['count']).reset_index()
size

    职业  违约  count
0  0.0   0   5550
1  0.0   1   1842
2  1.0   0    799
3  1.0   1    673
4  2.0   0    800
5  2.0   1    266
6  3.0   0     12
7  3.0   1      3
8  4.0   0     35
9  4.0   1     18

In [97]:
px.scatter(size,x='职业',y='违约',size='count')

In [98]:
dict1=todict(userinfo_df['教育程度'])
dict1
userinfo_df=userinfo_df.replace(dict1)

C:\Users\27968\AppData\Local\Temp\ipykernel_41384\159206469.py:3: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [99]:
userinfo_df

                           new_user_id  性别   职业  教育程度 婚姻状态  户口类型
0     7259fe272934e0dc348092c37544a445   0  0.0     0   未婚  集体户口
1     0c87f6b1f7e0350a35841ba34df9d26a   1  0.0     0   离异  集体户口
2     74c53a62f15cc039864aefc41170f81b   1  0.0     1   离异  家庭户口
3     211f56f356fa6ecc6334bb73e52c7b16   1  1.0     2   离异  农业户口
4     07b0d9ac7924424894141b2fecfa0ee0   1  0.0     0   已婚  集体户口
...                                ...  ..  ...   ...  ...   ...
9995  6b8887024b4258aab9c7b655fd2a718f   1  0.0     0   离异  农业户口
9996  158dd40361cd883d37a30fc448cfa7da   1  0.0     1   未婚  集体户口
9997  12fd60bba16cb55cdf3ca81d7d3326b5   0  0.0     0   离异  其他户口
9998  180232fd2d1db5512be0fe554e58405c   1  1.0     1   未婚  家庭户口
9999  cd1b034b97878a461a471337c099e8d3   1  2.0     0   未婚  家庭户口

[10000 rows x 6 columns]

In [100]:
size_useinfo=userinfo_df.groupby(['职业','教育程度'])['new_user_id'].agg('count').reset_index()
size_useinfo

     职业  教育程度  new_user_id
0   0.0     0         2875
1   0.0     1         3246
2   0.0     2         1241
3   0.0     3           30
4   1.0     0          780
5   1.0     1          520
6   1.0     2          166
7   1.0     3            6
8   2.0     0          475
9   2.0     1          452
10  2.0     2          134
11  2.0     3            5
12  3.0     1            8
13  3.0     2            6
14  3.0     3            1
15  4.0     4           53

In [101]:
px.scatter(size_useinfo,x='职业',y='教育程度',size='new_user_id')

In [102]:
bank_df

,new_user_id,交易时间戳,交易类型,交易金额,工资收入标记,交易时间,交易年,交易月,交易日,交易时,交易分,交易秒
0,65b01fba105ee82613babff7c88929c5,58848407247,1,43.757548,0,2156-06-25 21:58:44,2156,6,25,21,58,44
1,65b01fba105ee82613babff7c88929c5,58849365297,1,42.143743,0,2156-06-27 00:35:29,2156,6,27,0,35,29
2,65b01fba105ee82613babff7c88929c5,58850118237,1,40.189051,0,2156-06-27 21:30:23,2156,6,27,21,30,23
3,65b01fba105ee82613babff7c88929c5,58850118447,1,40.189051,0,2156-06-27 21:30:44,2156,6,27,21,30,44
4,65b01fba105ee82613babff7c88929c5,58850244487,1,40.189051,0,2156-06-28 01:00:48,2156,6,28,1,0,48
...,...,...,...,...,...,...,...,...,...,...,...,...
1068419,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.749626,0,2157-10-01 07:31:27,2157,10,1,7,31,27
1068420,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.313940,0,2157-10-01 07:31:27,2157,10,1,7,31,27
1068421,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.313940,0,2157-10-01 07:31:27,2157,10,1,7,31,27
1068422,8909c0bd8a030659a64af64874f3a85d,59248782877,0,45.556734,0,2157-10-02 07:31:27,2157,10,2,7,31,27
1068423,8909c0bd8a030659a64af64874f3a85d,59248782877,0,42.864229,0,2157-10-02 07:31:27,2157,10,2,7,31,27

In [103]:
bank_df = bank_df[["new_user_id", "交易时间戳", "交易类型", "交易金额", "工资收入标记"]]
bank_df

,new_user_id,交易时间戳,交易类型,交易金额,工资收入标记
0,65b01fba105ee82613babff7c88929c5,58848407247,1,43.757548,0
1,65b01fba105ee82613babff7c88929c5,58849365297,1,42.143743,0
2,65b01fba105ee82613babff7c88929c5,58850118237,1,40.189051,0
3,65b01fba105ee82613babff7c88929c5,58850118447,1,40.189051,0
4,65b01fba105ee82613babff7c88929c5,58850244487,1,40.189051,0
...,...,...,...,...,...
1068419,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.749626,0
1068420,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.313940,0
1068421,8909c0bd8a030659a64af64874f3a85d,59247918877,1,46.313940,0
1068422,8909c0bd8a030659a64af64874f3a85d,59248782877,0,45.556734,0
1068423,8909c0bd8a030659a64af64874f3a85d,59248782877,0,42.864229,0

In [104]:
salary = bank_df[bank_df['工资收入标记'] == 1]
salary

,new_user_id,交易时间戳,交易类型,交易金额,工资收入标记
950,7ad5361fd9590ea88dc750aa0274332c,58934286877,0,47.070770,1
952,7ad5361fd9590ea88dc750aa0274332c,58935150877,0,46.203056,1
957,7ad5361fd9590ea88dc750aa0274332c,58948974877,0,46.554156,1
962,7ad5361fd9590ea88dc750aa0274332c,58960206877,0,47.046780,1
964,7ad5361fd9590ea88dc750aa0274332c,58976622877,0,46.116645,1
...,...,...,...,...,...
1065985,4f472d052f8e0e9c8e90e849cf1497e7,59223726877,0,46.753540,1
1066016,4f472d052f8e0e9c8e90e849cf1497e7,59248782877,0,46.922092,1
1066038,4f472d052f8e0e9c8e90e849cf1497e7,59273838877,0,46.985973,1
1066225,45e9ca6b1c0419cb96ae4652770cfadf,59118318877,0,46.440923,1
1066242,45e9ca6b1c0419cb96ae4652770cfadf,59145102877,0,46.738876,1

In [105]:
avg_salary=salary.groupby(['new_user_id'])["交易金额"].agg(["mean"])
avg_salary

                                       mean
new_user_id
00375b8a7a62da4f578f4f4464fc4228  44.964550
00872649357929f1f3d7fafbe484810b  46.415984
00e44c200eeb161df7d08ac1b79bd4a7  47.292812
02419b54629f540d3430e6ba8230aac4  45.600048
024c12c231362aa4206c001674abe30f  40.380961
...                                     ...
fdfcea9217eac320f5d2e30a58f356fa  42.958105
fe000bc1c6325b6df010187cca665a1e  46.980840
fed554907bfead73a15b053ecec59e11  47.292812
fee3ee14f7b2e42e86746d19115ef14a  47.061820
ffea401657d40332181dc2b2ef814553  46.749626

[556 rows x 1 columns]

In [106]:
avg_salary = avg_salary.rename(columns={'mean': '平均收入'})
avg_salary.reset_index(inplace=True)

In [107]:
merge = pd.merge(avg_salary, userinfo_df, on='new_user_id')
merge

                          new_user_id       平均收入  性别   职业  教育程度 婚姻状态  户口类型
0    00375b8a7a62da4f578f4f4464fc4228  44.964550   1  0.0     2   离异  家庭户口
1    00872649357929f1f3d7fafbe484810b  46.415984   2  4.0     4    4     4
2    00e44c200eeb161df7d08ac1b79bd4a7  47.292812   1  0.0     0   离异  集体户口
3    02419b54629f540d3430e6ba8230aac4  45.600048   1  0.0     1   离异  农业户口
4    024c12c231362aa4206c001674abe30f  40.380961   1  0.0     0   离异  家庭户口
..                                ...        ...  ..  ...   ...  ...   ...
551  fdfcea9217eac320f5d2e30a58f356fa  42.958105   1  0.0     1   未婚  农业户口
552  fe000bc1c6325b6df010187cca665a1e  46.980840   1  0.0     2   未婚  家庭户口
553  fed554907bfead73a15b053ecec59e11  47.292812   1  0.0     0   离异  其他户口
554  fee3ee14f7b2e42e86746d19115ef14a  47.061820   1  0.0     0   丧偶  家庭户口
555  ffea401657d40332181dc2b2ef814553  46.749626   1  0.0     0   离异  家庭户口

[556 rows x 7 columns]

In [108]:
px.scatter(x=merge["教育程度"], y=merge["平均收入"])